tambah test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -53,17 +53,17 @@ jobs:
           # ${{ fromJson(inputs.data).env }}
           # EOF
 
-          cat <<EOF > ./id_rsa
-          ${{ secrets.VPS_KEY }}
-          EOF
+          # cat <<EOF > ./id_rsa
+          # ${{ secrets.VPS_KEY }}
+          # EOF
 
-          chmod 600 ./id_rsa
+          # chmod 600 ./id_rsa
 
-          ssh-keyscan ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
+          # ssh-keyscan ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
 
       - name: clone project
         run: git clone --branch ${{ env.WIBU_BRANCH }} https://x-access-token:${{ secrets.WIBU_GIT_TOKEN }}@github.com/bipproduction/${{ env.WIBU_REPO }}.git ${{ env.WIBU_APP_VERSION }}
-      
+
       - name: handle .env
         working-directory: ${{ env.WIBU_APP_VERSION }}
         run: cat package.json
@@ -93,10 +93,14 @@ jobs:
         working-directory: ${{ env.WIBU_APP_VERSION }}
         run: rm -r node_modules
 
-      - name: mkdir target releases
-        run: |
-           ssh -o StrictHostKeyChecking=no -i ./id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
-           "mkdir -p ${{env.WIBU_TARGET_RELEASES_DIR}}"
+      - name: handle create dir releases
+        uses: appleboy/ssh-action@v1
+        with:
+          host: ${{ secrets.VPS_HOST }}
+          username: ${{ secrets.VPS_USER }}
+          key: ${{ secrets.VPS_KEY }}
+          script: |
+            mkdir -p ${{env.WIBU_TARGET_RELEASES_DIR}}
 
       - name: Deploy to VPS (New Version)
         uses: appleboy/scp-action@master
@@ -107,70 +111,59 @@ jobs:
           source: "${{ env.WIBU_APP_VERSION}}"
           target: "${{ env.WIBU_TARGET_RELEASES_DIR }}"
 
-      - name: deploy env
-        run: | 
-          ssh -o StrictHostKeyChecking=no -i ./id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
-          "echo \"${{ fromJson(inputs.data).env }}\" > ${{ env.WIBU_TARGET_WORKER_DIR }}/.env"
-      
-      - name: install and db push on project
-        run: |
-          ssh -o StrictHostKeyChecking=no -i ./id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
-          "cd ${{env.WIBU_TARGET_WORKER_DIR}} && bun install && bunx prisma db push"
-
-      - name: seed on project
-        continue-on-error: true
-        run:  |
-          ssh -o StrictHostKeyChecking=no -i ./id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
-          "cd ${{env.WIBU_TARGET_WORKER_DIR}} && bunx prisma db seed || true"
-
-      - name: check config
-        run: |
-          ssh-keyscan -t rsa,ecdsa,ed25519 ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
-          ssh -o StrictHostKeyChecking=yes -i ./id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} <<EOD
-          cd ${{ env.WIBU_TARGET_PROJECT_DIR }}
-          ECOSYSTEM_FILE="ecosystem.config.json"
-          if [[ ! -f "\$ECOSYSTEM_FILE" ]]; then
-            CONFIF=\$(bun /var/www/lib/generate-config.ts \
-              --name "${{ env.WIBU_NAME }}" \
-              --namespace "${{ env.WIBU_NAMESPACE }}" \
-              --count "${{ env.WIBU_COUNT }}")
-            if [[ -z "\$CONFIF" ]]; then
-              echo "Error: Failed to generate config"
-              exit 1
-            fi
-            echo "\$CONFIF" > "\$ECOSYSTEM_FILE"
-          fi
-          EOD
-
-      - name: create symbolic link and reload
-        run: |
-          ssh-keyscan -t rsa,ecdsa,ed25519 ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
-          ssh -o StrictHostKeyChecking=no -i ./id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} <<EOD
-          # Hapus symlink current jika ada (abaikan error jika tidak ada)
-          rm -rf ${{ env.WIBU_TARGET_CURRENT_DIR }} 2>&1 || true
-
-          # Buat symlink baru ke direktori worker terbaru
-          ln -sf ${{ env.WIBU_TARGET_WORKER_DIR }} ${{ env.WIBU_TARGET_CURRENT_DIR }}
-
-          # Reload PM2 jika sudah berjalan, atau mulai PM2 jika belum berjalan
-          pm2 reload ${{ env.WIBU_TARGET_PROJECT_DIR }}/ecosystem.config.json || \
-          pm2 start ${{ env.WIBU_TARGET_PROJECT_DIR }}/ecosystem.config.json
-
-          # Simpan konfigurasi PM2 agar persisten setelah reboot
-          pm2 save
-          EOD
-
-      - name: Deploy via SSH
+      - name: handle config on server
         uses: appleboy/ssh-action@v1
         with:
           host: ${{ secrets.VPS_HOST }}
           username: ${{ secrets.VPS_USER }}
           key: ${{ secrets.VPS_KEY }}
           script: |
-            ssh-keyscan -t rsa,ecdsa,ed25519 ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
-            ssh -o StrictHostKeyChecking=no -i ./id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} <<EOD
+            # deploy env
+            echo \"${{ fromJson(inputs.data).env }}\" > ${{ env.WIBU_TARGET_WORKER_DIR }}/.env
+
+            # install and db push
+            cd ${{env.WIBU_TARGET_WORKER_DIR}} && bun install && bunx prisma db push
+
+            # seed
+            cd ${{env.WIBU_TARGET_WORKER_DIR}} && bunx prisma db seed || true
+
+            # generate config
+            cd ${{ env.WIBU_TARGET_PROJECT_DIR }}
+            ECOSYSTEM_FILE="ecosystem.config.json"
+            if [[ ! -f "\$ECOSYSTEM_FILE" ]]; then
+              CONFIF=\$(bun /var/www/lib/generate-config.ts \
+                --name "${{ env.WIBU_NAME }}" \
+                --namespace "${{ env.WIBU_NAMESPACE }}" \
+                --count "${{ env.WIBU_COUNT }}")
+            if [[ -z "\$CONFIF" ]]; then
+              echo "Error: Failed to generate config"
+              exit 1
+            fi
+            echo "\$CONFIF" > "\$ECOSYSTEM_FILE"
+            fi
+
+      - name: handle current on server
+        uses: appleboy/ssh-action@v1
+        with:
+          host: ${{ secrets.VPS_HOST }}
+          username: ${{ secrets.VPS_USER }}
+          key: ${{ secrets.VPS_KEY }}
+          script: |
+            # Hapus symlink current jika ada (abaikan error jika tidak ada)
+            rm -rf ${{ env.WIBU_TARGET_CURRENT_DIR }} 2>&1 || true
+
+            # Buat symlink baru ke direktori worker terbaru
+            ln -sf ${{ env.WIBU_TARGET_WORKER_DIR }} ${{ env.WIBU_TARGET_CURRENT_DIR }}
+
+            # Reload PM2 jika sudah berjalan, atau mulai PM2 jika belum berjalan
+            pm2 reload ${{ env.WIBU_TARGET_PROJECT_DIR }}/ecosystem.config.json || \
+            pm2 start ${{ env.WIBU_TARGET_PROJECT_DIR }}/ecosystem.config.json
+
+            # Simpan konfigurasi PM2 agar persisten setelah reboot
+            pm2 save
+
+            # Update history
             bun /var/www/lib/history.ts --name "${{ env.WIBU_NAME }}" --namespace "${{ env.WIBU_NAMESPACE }}"
-            EOD
 
       - name: finish
         if: always()
@@ -178,4 +171,3 @@ jobs:
           curl -X POST -H "Content-Type: application/json" \
           -d '{"text": "Finish Deploy"}' \
           ${{ secrets.FBS_DB_URL }}/logs/build/${{ env.WIBU_NAMESPACE }}/log.json
-          
