tambahan

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -109,6 +109,57 @@ jobs:
           script: |
             mkdir -p ${{env.WIBU_TARGET_RELEASES_DIR}}
 
+      - name: Start Next.js app and run Playwright and save screenshot
+        continue-on-error: true
+        working-directory: ${{ env.WIBU_APP_VERSION }}
+        run: |
+          set -e  # Fail fast
+
+          # Jalankan server di background
+          bun run start --port 3000 &
+
+          # Simpan PID untuk nanti di-kill
+          SERVER_PID=$!
+
+          # Tunggu server siap (ganti sesuai kebutuhan kalau perlu)
+          echo "Waiting for server to be ready..."
+          sleep 120
+
+          # Install playwright
+          echo "Installing playwright..."
+          bun add playwright
+
+          # Install browser
+          bunx playwright install  
+
+          # Buat file sementara untuk script Playwright
+          cat <<EOF > take-screenshot.ts
+          import { chromium } from 'playwright';
+
+          (async () => {
+            console.log('Launching browser...');
+            const browser = await chromium.launch();
+            const page = await browser.newPage();
+            console.log('Navigating to localhost...');
+            await page.goto('http://localhost:3000');
+            console.log('Taking screenshot...');
+            await new Promise(resolve => setTimeout(resolve, 3000));
+            await page.screenshot({ fullPage: true, path: 'screenshot.png' });
+            await browser.close();
+          })();
+          EOF
+
+          # Jalankan script Playwright
+          echo "Running Playwright script..."
+          bun run take-screenshot.ts
+
+          # Tampilkan isi direktori
+            ls
+
+          # Matikan server
+          echo "Killing server with PID $SERVER_PID"
+          kill $SERVER_PID
+        
       - name: Deploy to VPS (New Version)
         uses: appleboy/scp-action@master
         with:
@@ -116,6 +167,15 @@ jobs:
           username: ${{ secrets.VPS_USER }}
           key: ${{ secrets.VPS_KEY }}
           source: "${{ env.WIBU_APP_VERSION}}"
+          target: "${{ env.WIBU_TARGET_RELEASES_DIR }}"
+
+      - name: Deploy screenshot to VPS 
+        uses: appleboy/scp-action@master
+        with:
+          host: ${{ secrets.VPS_HOST }}
+          username: ${{ secrets.VPS_USER }}
+          key: ${{ secrets.VPS_KEY }}
+          source: "${{ env.WIBU_APP_VERSION}}/screenshot.png"
           target: "${{ env.WIBU_TARGET_RELEASES_DIR }}"
 
       - name: handle install on vps
@@ -219,77 +279,8 @@ jobs:
             https://raw.githubusercontent.com/bipproduction/wibu-server/refs/heads/main/lib/history.ts?v=1 \
             | bun run - \
               --name "${{ env.WIBU_NAME }}" \
-              --namespace "${{ env.WIBU_NAMESPACE }}" 
+              --namespace "${{ env.WIBU_NAMESPACE }}"
 
-      - name: Start Next.js app and run Playwright and save screenshot
-        continue-on-error: true
-        working-directory: ${{ env.WIBU_APP_VERSION }}
-        run: |
-          set -e  # Fail fast
-
-          # Jalankan server di background
-          bun run start --port 3000 &
-      
-          # Simpan PID untuk nanti di-kill
-          SERVER_PID=$!
-      
-          # Tunggu server siap (ganti sesuai kebutuhan kalau perlu)
-          echo "Waiting for server to be ready..."
-          sleep 10
-      
-          # Install playwright
-          echo "Installing playwright..."
-          bun add playwright
-          bun add wait-on
-
-          # Install browser
-          bunx playwright install  
-
-          # Buat file sementara untuk script Playwright
-          cat <<EOF > take-screenshot.ts
-          import { chromium } from 'playwright';
-
-          (async () => {
-            console.log('Launching browser...');
-            const browser = await chromium.launch();
-            const page = await browser.newPage();
-            console.log('Navigating to localhost...');
-            await page.goto('http://localhost:3000');
-            console.log('Taking screenshot...');
-            await new Promise(resolve => setTimeout(resolve, 3000));
-            await page.screenshot({ fullPage: true, path: 'screenshot.png' });
-            await browser.close();
-          })();
-          EOF
-
-          bunx wait-on http://localhost:3000
-
-          # Jalankan script Playwright
-          echo "Running Playwright script..."
-          bun run take-screenshot.ts
-      
-          # Tampilkan isi direktori
-           ls -lh
-
-          # Konversi screenshot ke base64
-          BASE64_CONTENT=$(base64 screenshot.png | tr -d '\n')
-          echo "BASE64_CONTENT=$BASE64_CONTENT" >> $GITHUB_ENV
-      
-          # Matikan server
-          echo "Killing server with PID $SERVER_PID"
-          kill $SERVER_PID
-         
-      - name: upload screenshot
-        continue-on-error: true
-        uses: appleboy/ssh-action@v1
-        with:
-          host: ${{ secrets.VPS_HOST }}
-          username: ${{ secrets.VPS_USER }}
-          key: ${{ secrets.VPS_KEY }}
-          script: |
-            echo "${{ env.BASE64_CONTENT }}" | base64 -d > ${{ env.WIBU_TARGET_WORKER_DIR }}/screenshot.png
-            chmod 644 ${{ env.WIBU_TARGET_WORKER_DIR }}/screenshot.png
-          
       - name: update log error
         if: failure()
         continue-on-error: true
